version: '3'

services:
  userservice:
    image: kacestudio/javan-userservice
    build: 
      context: userservice
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql

  taxservice:
    image: kacestudio/javan-taxservice
    build: 
      context: taxservice
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - mysql

  adminer:
    image: adminer:4.8.0
    ports:
      - 8082:8080
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
    driver: local 
  rabbitmq_data: 
    driver: local
